---
# Monitoring role - Install Prometheus Node Exporter and optional monitoring tools

- name: Create node_exporter user
  user:
    name: node_exporter
    shell: /bin/false
    system: true
    create_home: false

- name: Download Node Exporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch_map[ansible_architecture] }}.tar.gz"
    dest: "/tmp/node_exporter.tar.gz"
    mode: '0644'

- name: Extract Node Exporter
  unarchive:
    src: "/tmp/node_exporter.tar.gz"
    dest: "/tmp"
    remote_src: true

- name: Copy Node Exporter binary
  copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch_map[ansible_architecture] }}/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    mode: '0755'
    remote_src: true

- name: Create Node Exporter systemd service
  copy:
    dest: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=Prometheus Node Exporter
      After=network.target

      [Service]
      Type=simple
      User=node_exporter
      Group=node_exporter
      ExecStart=/usr/local/bin/node_exporter {{ node_exporter_options }}
      SyslogIdentifier=node_exporter
      Restart=always

      [Install]
      WantedBy=multi-user.target
    mode: '0644'
  notify: restart node_exporter

- name: Start and enable Node Exporter
  systemd:
    name: node_exporter
    state: started
    enabled: true
    daemon_reload: true

- name: Allow Node Exporter through firewall
  ufw:
    rule: allow
    port: "9100"
    proto: tcp
    from_ip: "{{ item }}"
  loop: "{{ monitoring_allowed_ips }}"
  when:
    - enable_firewall | default(true)
    - monitoring_allowed_ips | length > 0

- name: Clean up temporary files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/tmp/node_exporter.tar.gz"
    - "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch_map[ansible_architecture] }}"
