---
# MariaDB installation and configuration

- name: Install MariaDB server
  apt:
    name:
      - "mariadb-server-{{ mariadb_version }}"
      - mariadb-client
      - python3-pymysql
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Ensure MariaDB is started and enabled
  service:
    name: mariadb
    state: started
    enabled: true

- name: Set MariaDB root password
  mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present
  when: mariadb_root_password is defined
  no_log: true

- name: Remove anonymous MariaDB users
  mysql_user:
    name: ''
    host_all: true
    state: absent
    login_unix_socket: /var/run/mysqld/mysqld.sock
  when: mariadb_remove_anonymous_users | default(true)

- name: Remove MariaDB test database
  mysql_db:
    name: test
    state: absent
    login_unix_socket: /var/run/mysqld/mysqld.sock
  when: mariadb_remove_test_db | default(true)

- name: Configure MariaDB bind address
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^bind-address'
    line: "bind-address = {{ mariadb_bind_address }}"
    state: present
  notify: restart mariadb
  when: mariadb_bind_address != '127.0.0.1'

- name: Create MariaDB databases
  mysql_db:
    name: "{{ item.name }}"
    encoding: "{{ item.encoding | default('utf8mb4') }}"
    collation: "{{ item.collation | default('utf8mb4_unicode_ci') }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop: "{{ mariadb_databases }}"
  when: mariadb_databases | length > 0

- name: Create MariaDB users
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    host: "{{ item.host | default('%') }}"
    priv: "{{ item.priv | default('*.*:ALL') }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop: "{{ mariadb_users }}"
  when: mariadb_users | length > 0
  no_log: true
